apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: demo
  meshConfig:
    accessLogEncoding: TEXT
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    pilot:
      jwksResolverExtraRootCA: |
        -----BEGIN CERTIFICATE-----
        MIIByDCCAW6gAwIBAgIRAPyfd5fmFyTMp9R+9IWc1V8wCgYIKoZIzj0EAwIwHTEb
        MBkGA1UEAxMSa2V5Y2xvYWsubGVhcm4uY29tMB4XDTIzMDEwNjE1Mjk1MVoXDTIz
        MDQwNjE1Mjk1MVowHTEbMBkGA1UEAxMSa2V5Y2xvYWsubGVhcm4uY29tMFkwEwYH
        KoZIzj0CAQYIKoZIzj0DAQcDQgAEcuLQHySeHsKXizK3lCOMGm9vRBVj8fTjR+n1
        Eiwvs5eyuy99wmlM5Ub+3aLyDPjYFIhn4DSEhBIW18v2d6zrrKOBjjCBizAOBgNV
        HQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUowJg1MmQBJXi
        Rxz5Fd61mOjvCTgwSQYDVR0RBEIwQIISa2V5Y2xvYWsubGVhcm4uY29tgiprZXlj
        bG9hay1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwwCgYIKoZIzj0E
        AwIDSAAwRQIhALSuK3kxfV4isIG0QcXMkVXsYc0KySVvm+oy8Rjn/HLoAiA45g3m
        AfwUb1H7UB4J7sjeOo/65+O+MVlKMt0V5llCpQ==
        -----END CERTIFICATE-----
