apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-keycloak
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.tls.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.tls.host }}
  gateways:
  - keycloak-gateway
  tls:
  - match: 
    - port: 443
      sniHosts:
      - {{ .Values.tls.host }}
    route:
    - destination:
        host: {{ "keycloak-service." }}{{ .Release.Namespace }}{{ ".svc.cluster.local" }}
        port:
          number: 8443
