apiVersion: v1
data:
  username: {{ .Values.database.username | b64enc  }}
  password: {{ .Values.database.password | b64enc  }}
kind: Secret
metadata:
  name: {{ .Values.database.secretName  }}
  namespace: {{ .Release.Namespace }}
type: Opaque
