---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: product-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "product.centralizer.io"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-vs
spec:
  hosts:
    - "product.centralizer.io"
  gateways:
    - product-gateway
  http:
  # - match:
  #   - headers:
  #       X-Proxy:
  #         exact: blue-proxy
  #     uri:
  #       prefix: "/"
  #     ignoreUriCase: true
  #   route:
  #     - destination:
  #         host: product-svc.default.svc.cluster.local
  #         port:
  #           number: 80
  # - match:
  #   - uri:
  #       prefix: /
  #   route:
  #     - destination:
  #         host: proxy-svc.default.svc.cluster.local
  #         port:
  #           number: 80
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: product-svc.default.svc.cluster.local
          port:
            number: 80