apiVersion: apps/v1
kind: Deployment
metadata:
  name:  product
  labels:
    name:  product
    app: product-svc
    use: product
    version: v1.0.0 
spec:
  selector:
    matchLabels:
      name: product
      app: product-svc
      use: product
      version: v1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  product
        app: product-svc
        use: product
        version: v1.0.0
    spec:
      containers:
      - image:  blueinit/demo-backend:1.0.0
        imagePullPolicy: IfNotPresent
        name:  product
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: "100m"
            memory: "256Mi"                
        ports:
        - containerPort:  8080
          name:  default
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always    
      serviceAccountName: product
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: product-svc
