 # ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spike-vs
  namespace: istio-system 
spec:
  hosts:
    - {{ .Values.tls.host }}
  gateways:
    - spike-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ "spike." }}{{ .Release.Namespace }}{{ ".svc.cluster.local" }}
        port:
          number: 80   
 
