apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-vs
spec:
  hosts:
    - "demo.centralizer.io"
  gateways:
    - demo-gateway
  http:
  - match:
    - headers:
        X-Proxy:
          exact: blue-proxy
      uri:
        prefix: "/"
      ignoreUriCase: true
    route:
      - destination:
          host: demo-svc.default.svc.cluster.local
          port:
            number: 80
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: proxy-svc.default.svc.cluster.local
          port:
            number: 80
